const $=s=>document.querySelector(s),esc=t=>String(t).replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
let S=Store.get('db')||seed(),me=Store.get('me'),view='home',cur=null,mi=null,adminTab='Overview';
const save=()=>Store.set('db',S),U=id=>S.users.find(u=>u.id===id)||{id,name:id,c:0},tm=ts=>{const m=Math.round((Date.now()-ts)/6e4);return m<1?'now':m<60?m+'m':m<1440?Math.round(m/60)+'h':Math.round(m/1440)+'d'};
const av=(u,on)=>`<div class="av ${on?'on':''}" style="background:${C[u.c]}" role="img" aria-label="${esc(u.name)} avatar">${esc(u.name[0])}</div>`;
const key=o=>[me,o].sort().join('|'),convo=o=>S.convos[key(o)]||(S.convos[key(o)]=[]);
const fr=()=>S.friends[me]||(S.friends[me]=[]),isBlocked=o=>(S.blocked[me]||[]).includes(o)||(S.blocked[o]||[]).includes(me);
function toast(m){const e=document.createElement('div');e.className='toast';e.textContent=m;$('#toasts').append(e);setTimeout(()=>e.remove(),2800)}
function modal(h){const m=$('#modal');m.innerHTML=`<div class="box" role="dialog" aria-modal="true">${h}</div>`;m.hidden=false;const f=m.querySelector('input,select,textarea,button');f&&f.focus()}
const close=()=>{$('#modal').hidden=true};
function confirmBox(msg,fn){modal(`<h3>Are you sure?</h3><p>${esc(msg)}</p><div class="row"><button class="dan" id="yes">Confirm</button><button onclick="close()">Cancel</button></div>`);$('#yes').onclick=()=>{close();fn()}}
function theme(){const t=Store.get('theme','system');document.documentElement.dataset.theme=t==='system'?(matchMedia('(prefers-color-scheme:dark)').matches?'dark':'light'):t}
// ---------- AUTH (demo only) ----------
function loginView(){$('#app').innerHTML=`<div class="login card"><div class="logo"><i>✦</i>CampusChat</div><p class="mute">Stay connected. Stay in the loop.</p>
<label>School username<input id="u" placeholder="student1" autocomplete="off"></label><label>Password<input id="p" type="password" placeholder="demo"></label>
<div class="row"><button class="pri grow" id="li">Log In</button><button class="grow" id="ca">Create Account</button></div>
<p class="mute">⚠ Demo only: no real security. Try student1, student2, student3 or teacher1 (moderator) with password “demo”.</p></div>`;
$('#li').onclick=()=>{const u=U($('#u').value.trim().toLowerCase());if(!S.users.find(x=>x.id===u.id)||$('#p').value!=='demo')return toast("That username or password doesn't match.");if(S.suspended.includes(u.id))return toast('This account is suspended.');me=u.id;Store.set('me',me);boot()};
$('#ca').onclick=()=>modal(`<h3>Welcome! Tell us a bit</h3><label>Display name<input id="n" maxlength="30"></label><label>Username<input id="nu" maxlength="20"></label><label>School<input id="sc"></label><label>Grade<select id="gr"><option>9</option><option>10</option><option>11</option><option>12</option></select></label><label>Short bio<input id="bi" maxlength="80"></label><p class="mute">We never ask for address, phone number or location.</p><button class="pri" id="mk">Create account</button>`);
document.addEventListener('click',e=>{if(e.target.id==='mk'){const id=$('#nu').value.trim().toLowerCase().replace(/[^a-z0-9_]/g,''),n=$('#n').value.trim();if(!id||!n)return toast('Please enter a name and username.');if(S.users.find(x=>x.id===id))return toast('That username is taken.');S.users.push({id,name:n,bio:$('#bi').value||`Grade ${$('#gr').value}`,role:'student',c:Math.floor(Math.random()*8),school:$('#sc').value});save();me=id;Store.set('me',me);close();boot()}})}
const NAV=[['home','🏠','Home'],['messages','💬','Messages'],['friends','👥','Friends'],['moments','✨','Stories'],['discover','🧭','Discover'],['notifs','🔔','Notifications'],['settings','⚙️','Settings']];
function boot(){if(!me)return loginView();const u=U(me);if(u.role==='admin'&&!NAV.find(n=>n[0]==='admin'))NAV.push(['admin','🛡️','Moderation']);go(view)}
function go(v){view=v;const u=U(me),n=S.notifs.length,nav=NAV.map(([k,i,l])=>`<button class="${k===v?'on':''}" data-go="${k}" aria-label="${l}">${i}<span>${l}${k==='notifs'&&n?` <b class="badge">${n}</b>`:''}</span></button>`).join('');
$('#app').innerHTML=`<div class="shell"><nav class="side" aria-label="Main"><div class="logo"><i>✦</i><span>CampusChat</span></div>${nav}<div class="grow"></div><div class="item" data-go="profile" tabindex="0" role="button">${av(u)}<span><b>${esc(u.name)}</b><br><span class="mute">@${esc(u.id)}</span></span></div></nav>
<main id="main"></main><aside class="right" id="right"></aside></div><nav class="bottom" aria-label="Mobile">${NAV.slice(0,6).map(([k,i,l])=>`<button data-go="${k}" aria-label="${l}">${i}</button>`).join('')}</nav>`;
document.querySelectorAll('[data-go]').forEach(b=>{b.onclick=()=>go(b.dataset.go);b.onkeydown=e=>e.key==='Enter'&&go(b.dataset.go)});
$('#main').innerHTML='<div class="skel"></div>';setTimeout(()=>{({home,messages,friends,moments,discover,notifs,profile,settings,admin})[v]();rightbar()},120)}
function rightbar(){const on=fr().filter(f=>f.length%2||true).slice(0,4);$('#right').innerHTML=`<div class="card"><b>Online now</b>${on.map(f=>`<div class="item" onclick="openChat('${f}')">${av(U(f),1)}${esc(U(f).name)}</div>`).join('')||'<p class="empty">No friends online.</p>'}</div><div class="card"><b>Announcements</b>${S.news.slice(0,2).map(n=>`<p class="mute">📣 ${esc(n.t)}</p>`).join('')}</div>`}
const openChat=o=>{cur=o;go('messages')};
// ---------- VIEWS ----------
function home(){const h=new Date().getHours(),g=h<12?'morning':h<18?'afternoon':'evening';
$('#main').innerHTML=`<h1>Good ${g}, ${esc(U(me).name)}</h1><div class="row card"><button class="pri" onclick="go('messages')">New Message</button><button onclick="go('friends')">Add Friend</button><button onclick="newMoment()">Create Story</button><button onclick="go('discover')">View Announcements</button></div>
<h3>Recent conversations</h3><div class="card">${convList()}</div><h3>Stories</h3><div class="row card">${momRing()}</div><h3>School updates</h3><div class="grid">${S.news.map(newsCard).join('')}</div>`}
function convList(){const ids=fr().filter(f=>convo(f).length);return ids.length?ids.map(f=>{const m=convo(f).at(-1);return`<div class="item" onclick="openChat('${f}')" tabindex="0" role="button">${av(U(f))}<div class="grow"><b>${esc(U(f).name)}</b><br><span class="mute">${esc(m.t.slice(0,40))}</span></div><span class="mute">${tm(m.ts)}</span>${m.f!==me?'<span class="badge" aria-label="unread">●</span>':''}</div>`}).join(''):'<div class="empty">No conversations yet.<br>Start a conversation with a friend.</div>'}
const momRing=()=>S.moments.length?S.moments.map((m,i)=>`<div class="item" onclick="viewMoment(${i})" tabindex="0" role="button"><div class="ring">${av(U(m.u))}</div><b>${esc(U(m.u).name)}</b></div>`).join(''):'<div class="empty">No Moments yet.</div>';
const newsCard=n=>`<div class="card"><span class="badge" style="background:var(--brand)">${esc(n.cat)}</span><h4>${esc(n.t)}</h4><p class="mute">${esc(n.d)}</p><small>${esc(n.a)}</small><br><button onclick="modal('<h3>${esc(n.t)}</h3><p>${esc(n.d)}</p><button onclick=close()>Close</button>')">View Details</button></div>`;
function messages(){const ids=fr();cur=cur||ids[0];const list=ids.map(f=>`<div class="item ${f===cur?'on':''}" onclick="cur='${f}';messages()">${av(U(f),1)}<b>${esc(U(f).name)}</b></div>`).join('')||'<div class="empty">No conversations yet.</div>';
const ms=cur?convo(cur):[];$('#main').innerHTML=`<div class="chat"><div class="card">${list}</div><div class="card" style="display:flex;flex-direction:column;overflow:hidden">${cur?`<div class="row">${av(U(cur),1)}<b class="grow">${esc(U(cur).name)}<br><small class="mute">Online</small></b><button disabled title="Calls need a backend">📞</button><button onclick="reportUser('${cur}')">Report</button><button onclick="blockUser('${cur}')">Block</button></div>
<div class="msgs" id="ms" aria-live="polite">${ms.map((m,i)=>`<div class="bub ${m.f===me?'me':''}" onclick="react(${i})" title="Tap to react"><span>${esc(m.t)}</span>${m.r?` ${m.r}`:''}<small>${tm(m.ts)}${m.f===me?' · Seen':''}</small></div>`).join('')}<div class="mute" id="ty" hidden>typing…</div></div>
<div class="row"><button aria-label="Emoji" onclick="$('#mi').value+='😂'">😊</button><button aria-label="Image (needs backend)" disabled>🖼️</button><input class="grow" id="mi" placeholder="Message" aria-label="Message" style="margin:0"><button class="pri" id="sd">Send</button></div>`:'<div class="empty">Pick a friend to start chatting.</div>'}</div></div>`;
if(cur){const s=$('#ms');s.scrollTop=1e9;$('#sd').onclick=send;$('#mi').onkeydown=e=>e.key==='Enter'&&send()}}
function send(){const v=$('#mi').value.trim();if(!v)return toast('Please enter a message.');if(isBlocked(cur))return toast("You can't message this user.");convo(cur).push({f:me,t:v,ts:Date.now()});save();messages();$('#ty').hidden=false;const o=cur;setTimeout(()=>{convo(o).push({f:o,t:['lmao 😭','ok sounds good','see you there!'][Math.random()*3|0],ts:Date.now()});save();if(view==='messages'&&cur===o)messages()},1500)}
function react(i){const m=convo(cur)[i];m.r=m.r?'':'❤️';save();messages()}
function blockUser(o){confirmBox(`Block ${U(o).name}? They won't be able to message you or send requests.`,()=>{(S.blocked[me]=S.blocked[me]||[]).push(o);S.friends[me]=fr().filter(x=>x!==o);cur=null;save();toast('User blocked.');go(view)})}
function reportUser(o){modal(`<h3>Report ${esc(U(o).name)}</h3><select id="rc">${['Harassment','Bullying','Spam','Inappropriate content','Impersonation','Other'].map(c=>`<option>${c}</option>`).join('')}</select><textarea id="rd" placeholder="What happened?" maxlength="300"></textarea><div class="row"><button class="dan" id="rs">Submit report</button><button onclick="close()">Cancel</button></div>`);$('#rs').onclick=()=>{const c=$('#rc').value,d=$('#rd').value;close();confirmBox('Submit this report to school moderators?',()=>{S.reports.push({id:100+S.reports.length+1,target:o,by:me,cat:c,desc:d,ts:Date.now(),status:'Pending'});save();toast('Report sent. Thank you.')})}}
function friends(){const f=fr(),ri=S.reqIn[me]||[],ro=S.reqOut[me]||[],row=(id,b)=>`<div class="item">${av(U(id),1)}<div class="grow"><b>${esc(U(id).name)}</b><br><span class="mute">@${esc(id)}</span></div>${b}</div>`;
$('#main').innerHTML=`<h1>Friends</h1><div class="card"><div class="row"><input id="fs" class="grow" placeholder="Search username" aria-label="Search username" style="margin:0"><button class="pri" id="fb">Search</button></div><div id="fr"></div></div>
<div class="card"><b>Requests</b>${ri.map(i=>row(i,`<button class="pri" onclick="acc('${i}')">Accept</button><button onclick="decl('${i}')">Decline</button>`)).join('')||'<p class="mute">No incoming requests.</p>'}${ro.map(i=>row(i,`<span class="mute">Pending</span><button onclick="canc('${i}')">Cancel</button>`)).join('')}</div>
<div class="card"><b>Your friends</b>${f.map(i=>row(i,`<button onclick="openChat('${i}')">Message</button><button onclick="rem('${i}')">Remove</button>`)).join('')||'<div class="empty">You haven\'t added anyone yet.</div>'}</div>`;
$('#fb').onclick=()=>{const q=$('#fs').value.trim().toLowerCase().replace('@',''),u=S.users.find(x=>x.id===q);$('#fr').innerHTML=!u||u.id===me?'<p class="mute">That username doesn\'t exist.</p>':row(u.id,fr().includes(u.id)?'<span class="mute">Friends</span>':`<button class="pri" onclick="addF('${u.id}')">Add Friend</button>`)}}
function addF(o){if(isBlocked(o))return toast("You can't add this user.");(S.reqOut[me]=S.reqOut[me]||[]).push(o);(S.reqIn[o]=S.reqIn[o]||[]).push(me);save();toast('Request sent.');friends()}
function acc(o){fr().push(o);(S.friends[o]=S.friends[o]||[]).push(me);S.reqIn[me]=S.reqIn[me].filter(x=>x!==o);save();toast('Friend added!');friends()}
function decl(o){S.reqIn[me]=S.reqIn[me].filter(x=>x!==o);save();friends()}
function canc(o){S.reqOut[me]=S.reqOut[me].filter(x=>x!==o);S.reqIn[o]=(S.reqIn[o]||[]).filter(x=>x!==me);save();friends()}
function rem(o){confirmBox('Remove this friend?',()=>{S.friends[me]=fr().filter(x=>x!==o);save();friends()})}
function moments(){$('#main').innerHTML=`<h1>Stories</h1><button class="pri" onclick="newMoment()">+ Create a Moment</button><div class="row card" style="margin-top:14px">${momRing()}</div><p class="mute">Moments disappear after 24 hours.</p>`}
function newMoment(){modal(`<h3>New Moment</h3><textarea id="mt" maxlength="120" placeholder="What's happening? Add emoji 🎉"></textarea><div class="row">${C.map(c=>`<button class="bgp" data-c="${c}" aria-label="Color ${c}" style="background:${c};width:36px;height:36px;padding:0"></button>`).join('')}</div><br><div class="row">${['😂','🔥','🎉','🏀'].map(e=>`<button onclick="$('#mt').value+='${e}'">${e}</button>`).join('')}</div><br><button class="pri" id="mp">Post for 24h</button>`);let bg=C[0];document.querySelectorAll('.bgp').forEach(b=>b.onclick=()=>bg=b.dataset.c);$('#mp').onclick=()=>{const t=$('#mt').value.trim();if(!t)return toast('Please add some text.');S.moments.unshift({id:Date.now(),u:me,t,bg,ts:Date.now()});save();close();toast('Moment posted!');go(view)}}
function viewMoment(i){mi=i;const ms=S.moments.filter(m=>Date.now()-m.ts<864e5),m=ms[i];if(!m)return close();if(S.blocked[m.u]?.includes(me))return toast("You can't view this Moment.");
modal(`<div class="bars">${ms.map((_,k)=>`<b class="${k<=i?'d':''}"></b>`).join('')}</div><div class="row">${av(U(m.u))}<b class="grow">${esc(U(m.u).name)} <span class="mute">${tm(m.ts)}</span></b><button aria-label="Close" onclick="close()">✕</button></div><div class="mom" style="background:${m.bg}">${esc(m.t)}</div><div class="row" style="margin-top:10px"><button ${i?'':'disabled'} onclick="viewMoment(${i-1})">‹</button><button onclick="toast('Reacted ❤️')">❤️</button><input id="mr" class="grow" placeholder="Reply" aria-label="Reply" style="margin:0"><button onclick="$('#mr').value?(toast('Reply sent'),close()):toast('Please enter a reply.')">Send</button><button ${i<ms.length-1?'':'disabled'} onclick="viewMoment(${i+1})">›</button></div>`)}
function discover(){const cats=['All','School News','Clubs','Sports','Events','Student Projects','Announcements'];$('#main').innerHTML=`<h1>Discover</h1><div class="tabs">${cats.map(c=>`<button class="${c==='All'?'on':''}" data-c="${c}">${c}</button>`).join('')}</div><div class="grid" id="dg">${S.news.map(newsCard).join('')}</div>`;document.querySelectorAll('.tabs button').forEach(b=>b.onclick=()=>{document.querySelectorAll('.tabs button').forEach(x=>x.classList.remove('on'));b.classList.add('on');const l=S.news.filter(n=>b.dataset.c==='All'||b.dataset.c.includes(n.cat));$('#dg').innerHTML=l.map(newsCard).join('')||'<div class="empty">Nothing here yet.</div>'})}
function notifs(){$('#main').innerHTML=`<h1>Notifications</h1>${S.notifs.map(n=>`<div class="card item" onclick="S.notifs=S.notifs.filter(x=>x.id!==${n.id});save();go('${n.go}')" tabindex="0" role="button"><span class="grow">${esc(n.txt)}</span><span class="mute">${tm(n.ts)}</span></div>`).join('')||'<div class="empty">You\'re all caught up.</div>'}`}
function profile(){const u=U(me);$('#main').innerHTML=`<div class="card" style="text-align:center"><div style="display:flex;justify-content:center"><div class="av" style="width:96px;height:96px;font-size:2.4rem;background:${C[u.c]}">${esc(u.name[0])}</div></div><h2>${esc(u.name)}</h2><div class="mute">@${esc(u.id)}</div><p>${esc(u.bio)}</p><div class="row" style="justify-content:center"><span><b>${fr().length}</b> Friends</span><span><b>${S.moments.filter(m=>m.u===me).length}</b> Moments</span></div><br><button class="pri" onclick="editProfile()">Edit Profile</button> <button onclick="go('settings')">Settings</button></div>`}
function editProfile(){const u=U(me);modal(`<h3>Edit profile</h3><label>Display name<input id="en" value="${esc(u.name)}"></label><label>Bio<input id="eb" value="${esc(u.bio)}"></label><div class="row">${C.map((c,i)=>`<button class="cp" data-i="${i}" aria-label="Avatar color ${i+1}" style="background:${c};width:36px;height:36px;padding:0"></button>`).join('')}</div><br><button class="pri" id="es">Save</button>`);document.querySelectorAll('.cp').forEach(b=>b.onclick=()=>u.c=+b.dataset.i);$('#es').onclick=()=>{if(!$('#en').value.trim())return toast('Please enter a name.');u.name=$('#en').value.trim();u.bio=$('#eb').value;save();close();toast('Profile updated.');go('profile')}}
function settings(){const t=Store.get('theme','system'),P=S.prefs,sel=(k,o)=>`<select data-p="${k}">${o.map(x=>`<option ${P[k]===x?'selected':''}>${x}</option>`).join('')}</select>`;
$('#main').innerHTML=`<h1>Settings</h1><div class="card"><b>Appearance</b><select id="th">${['system','light','dark'].map(x=>`<option ${t===x?'selected':''}>${x}</option>`).join('')}</select></div>
<div class="card"><b>Privacy</b><br>Who can message me?${sel('msg',['Everyone','Friends','Nobody'])}Who can add me?${sel('add',['Everyone','Friends of friends','Nobody'])}Who can view my Moments?${sel('moments',['Everyone','Friends','Nobody'])}</div>
<div class="card"><b>Safety</b><p class="mute">Blocked: ${(S.blocked[me]||[]).map(i=>esc(U(i).name)).join(', ')||'none'}</p><button onclick="toast('Thanks, a moderator will review it.')">Report a problem</button></div>
<div class="card"><b>Account</b><br><br><button onclick="modal('<h3>Change password</h3><p>Passwords need a real backend. Demo accounts use “demo”.</p><button onclick=close()>OK</button>')">Change password</button> <button class="dan" id="lo">Log out</button></div>`;
$('#th').onchange=e=>{Store.set('theme',e.target.value);theme()};document.querySelectorAll('[data-p]').forEach(s=>s.onchange=()=>{S.prefs[s.dataset.p]=s.value;save();toast('Saved.')});$('#lo').onclick=()=>{me=null;Store.set('me',null);boot()}}
function admin(){if(U(me).role!=='admin'){$('#main').innerHTML='<div class="empty">Moderators only.</div>';return}
const tabs=['Overview','Reports','Users','Announcements'];let h=`<h1>Moderation</h1><div class="tabs">${tabs.map(t=>`<button class="${t===adminTab?'on':''}" onclick="adminTab='${t}';admin()">${t}</button>`).join('')}</div>`;
if(adminTab==='Overview')h+=`<div class="grid">${[['Total users',S.users.length],['Active users',S.users.length-S.suspended.length],['Pending reports',S.reports.filter(r=>r.status==='Pending').length],['Messages today',Object.values(S.convos).flat().length]].map(([a,b])=>`<div class="card"><div class="mute">${a}</div><h2>${b}</h2></div>`).join('')}</div>`;
if(adminTab==='Reports')h+=`<div class="card"><table><tr><th>ID</th><th>User</th><th>By</th><th>Category</th><th>Status</th><th></th></tr>${S.reports.map(r=>`<tr><td>#${r.id}</td><td>@${esc(r.target)}</td><td>@${esc(r.by)}</td><td title="${esc(r.desc)}">${esc(r.cat)}</td><td>${r.status}</td><td><button onclick="ra(${r.id},'Reviewed')">Review</button> <button onclick="ra(${r.id},'Dismissed')">Dismiss</button> <button onclick="ra(${r.id},'Warned')">Warn</button> <button class="dan" onclick="ra(${r.id},'Suspended')">Suspend</button></td></tr>`).join('')}</table></div>`;
if(adminTab==='Users')h+=`<div class="card">${S.users.map(u=>`<div class="item">${av(u)}<span class="grow">${esc(u.name)} @${esc(u.id)}</span>${S.suspended.includes(u.id)?'<span class="badge">Suspended</span>':''}</div>`).join('')}</div>`;
if(adminTab==='Announcements')h+=`<div class="card"><input id="at" placeholder="Title"><input id="ad" placeholder="Description"><select id="ac">${['General','Sports','Clubs','Events','Emergency'].map(c=>`<option>${c}</option>`).join('')}</select><button class="pri" onclick="pa()">Publish</button></div>`;
$('#main').innerHTML=h}
function pa(){const t=$('#at').value.trim();if(!t)return toast('Please enter a title.');S.news.unshift({id:Date.now(),t,d:$('#ad').value,cat:$('#ac').value,a:U(me).name});save();toast('Announcement published.')}
function ra(id,st){const r=S.reports.find(x=>x.id===id),f=()=>{r.status=st;if(st==='Suspended')S.suspended.push(r.target);save();admin()};st==='Suspended'||st==='Warned'?confirmBox(`${st} @${r.target}?`,f):f()}
// ---------- SEARCH + SHORTCUTS ----------
function search(){modal(`<input id="gs" placeholder="Search users, Moments, announcements…" aria-label="Global search"><div id="gr"></div>`);$('#gs').oninput=e=>{const q=e.target.value.toLowerCase();if(!q)return $('#gr').innerHTML='';const r=[...S.users.filter(u=>(u.id+u.name).toLowerCase().includes(q)).map(u=>'@'+u.id+' · '+u.name),...S.news.filter(n=>(n.t+n.d).toLowerCase().includes(q)).map(n=>'📣 '+n.t),...S.moments.filter(m=>m.t.toLowerCase().includes(q)).map(m=>'✨ '+m.t)];$('#gr').innerHTML=r.map(x=>`<div class="item">${esc(x)}</div>`).join('')||'<p class="empty">No results.</p>'}}
document.addEventListener('keydown',e=>{if(e.key==='Escape')close();if(!me)return;if((e.ctrlKey||e.metaKey)&&e.key==='k'){e.preventDefault();search()}if((e.ctrlKey||e.metaKey)&&e.key==='/'){e.preventDefault();modal('<h3>Shortcuts</h3><p><kbd>Ctrl+K</kbd> Search<br><kbd>Esc</kbd> Close<br><kbd>Enter</kbd> Send<br><kbd>Ctrl+/</kbd> This menu</p>')}});
theme();boot();
